{% set name = "osqp" %}
{% set version = "1.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0877552e325ff4cc1c676796ba482904eb4b66e750eff5b91df3273201f5ed00

build:
  number: 0
  skip: true # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - pybind11
    - scikit-build-core
    - setuptools_scm
    - setuptools
    - numpy  {{ numpy }}
    - blas
    - openblas
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('openblas') }}
    - numpy >=1.7
    - scipy  >=0.13.2
    - jinja2
    - joblib

test:
  imports:
    - osqp
    - osqp.codegen
  requires:
    - pytest >=6
    - pytorch
    - pip
  commands:
    - pip check
    # codegen tests are disabled because they require an incompatible ABI
    - python -m pytest --pyargs osqp -k "not codegen"

about:
  home: https://osqp.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.
    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/docs/get_started/python.html
  dev_url: https://github.com/osqp/osqp-python

extra:
  recipe-maintainers:
    - djsutherland
    - h-vetinari
    - bstellato
    - gbanjac
    - jayfurmanek
