{% set name = "osqp" %}
{% set version = "1.0.4" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0877552e325ff4cc1c676796ba482904eb4b66e750eff5b91df3273201f5ed00
  patches:
    - patches/0001-unvendor.patch 

build:
  number: 1
  skip: true # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja-base
    - numpy
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - scikit-build-core
    - pybind11
    - libosqp 1.0.0
    - numpy
  run:
    - python
    - setuptools
    - numpy >=1.7.0
    - scipy >=0.13.2
    - libosqp # bounds through run_exports 
    - jinja2
    - joblib

test:
  imports:
    - osqp
    - osqp.codegen
  requires:
    - pip
    - pytorch  # [py<314]
    - pytest >=6
  commands:
    - pip check
    # codegen tests are disabled because they require an incompatible ABI
    - python -m pytest --pyargs osqp -k "not codegen"  # [py<314]

    # TODO: remove this once pytorch py314 available in the channel
    - python -c "import osqp, pathlib; (pathlib.Path(osqp.__file__).parent/'tests'/'nn_test.py').unlink(missing_ok=True)"  # [py>=314]
    - python -m pytest --pyargs osqp -k "not codegen and not nn"  # [py>=314]

about:
  home: https://osqp.org
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.
    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/docs/get_started/python.html
  dev_url: https://github.com/osqp/osqp-python

extra:
  recipe-maintainers:
    - djsutherland
    - h-vetinari
    - bstellato
    - gbanjac
    - jayfurmanek
