{% set name = "osqp" %}
{% set osqp_python_version = "0.6.1" %}
{% set osqp_version = "0.6.0" %}
{% set qdldl_version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ osqp_python_version }}

source:
  - url: https://github.com/oxfordcontrol/osqp-python/archive/v{{ osqp_python_version }}.tar.gz
    fn: osqp-python-{{ osqp_python_version }}.tar.gz
    sha256: bfd8ccc4ccf2c7be1e8798bcc828e9b773a707deb2678a62d82396048e009742
    patches:
    - patches/0001-setup-use-NMake-on-windows.patch
    - patches/0002-setup-do-not-use-different-output-folder-on-windows.patch
    - patches/0003-also-use-NMake-in-codegen.patch
    - patches/0004-Disable-MKL-Tests-on-nonx86.patch     # [not x86_64]

  - url: https://github.com/oxfordcontrol/osqp/archive/v{{ osqp_version }}.tar.gz
    fn: osqp-{{ osqp_version }}.tar.gz
    sha256: 6e00d11d1f88c1e32a4419324b7539b89e8f9cbb1c50afe69f375347c989ba2b
    folder: osqp_sources
  - url: https://github.com/oxfordcontrol/qdldl/archive/v{{ qdldl_version }}.tar.gz
    fn: qdldl-{{ qdldl_version }}.tar.gz
    sha256: 4eaed3b2d66d051cea0a57b0f80a81fc04ec72c8a906f8020b2b07e31d3b549c
    folder: osqp_sources/lin_sys/direct/qdldl/qdldl_sources

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py==27 and (win or (not x86_64))]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make                           # [unix]
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.13.2
    - future
    - vs2015_runtime                 # [win]

test:
  imports:
    - osqp
    - osqp.codegen
    - osqppurepy
  requires:
    # some of the tests need mkl-specific solvers
    - blas=*=mkl                     # [x86_64]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pytest
    - make                           # [unix]
  commands:
    # codegen interface requires compiler + cmake
    - python -m pytest --pyargs osqp                    # [not win]
    # TODO: windows codegen tests are currently failing on azure
    - python -m pytest --pyargs osqp -k "not codegen_"  # [win]

about:
  home: https://osqp.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python interface for OSQP, the Operator Splitting QP Solver'
  description: |
    Python interface for OSQP, the Operator Splitting QP Solver.

    To use the `codegen` interface, install `cmake` and an appropriate
    compiler version. (We don't install this by default.)
  doc_url: https://osqp.org/
  dev_url: http://github.com/oxfordcontrol/osqp-python

extra:
  recipe-maintainers:
    - dougalsutherland
    - h-vetinari
    - bstellato
    - gbanjac
    - jayfurmanek
