# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "GkkUTA9qwKFvKkQ4WV4AFqaoyPmL0XFJD30al1ZfHMrb3LQ2HDFWgJNXN5t4xuahj00VJJyl5nL4gWcFIDht1XlCZ4YeyyOSUG6MRsi7Zxw1QcrNLHyHJu1mPc/Sx777CnyISCM/yCeEGMDW8StHUTHQmTnriSbKCKMPPGgsm3tGBAOFQ7jBLWlLwTVzIiFCxjpqN1ixq7XZWhTY/1i3De5q80h7ipDUkAuF3MnfM9LgrdShmrkU5TCjshRpOt/f8Df35BdGweff3lfeUKSXf9ryt6XzAf19ZUPNBJlEv6DtriRp1BxgiEgD5tZUVW7STREqjtO1uQJY2E9tMg93c6SryJgmZcwBLK5yjrIvf8GeVzqRiROG83lYJpYIwYFVLIQVti3Ih375qzeKXADLTwyclC/4mz6wnItRNlUW2sUifhTYQLsxiwFYySE9QRVIWTMLDk/4vsfSx7hC09taqoCn07+FPPO3d3WQAAD7wIJZCK3SSUfdgejWDaUr8g15T/PG7CoeN3vwWmk0Nd7t2Sa3MstePjjrJ2+hhfOpnyxR1NA12PnzL8fhsMA5MJV9KI/vLcXHag0fJ1Jr2igFHePbMA2r54fKzIyHQ2PfUMhjvFSaeCZpUt95ubvVh+qBjqejFVxxwxDzWeyHzTgcvLVwIc8cRrtotUH7BbgG75g="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
