travis:
  secure:
    BINSTAR_TOKEN: GkkUTA9qwKFvKkQ4WV4AFqaoyPmL0XFJD30al1ZfHMrb3LQ2HDFWgJNXN5t4xuahj00VJJyl5nL4gWcFIDht1XlCZ4YeyyOSUG6MRsi7Zxw1QcrNLHyHJu1mPc/Sx777CnyISCM/yCeEGMDW8StHUTHQmTnriSbKCKMPPGgsm3tGBAOFQ7jBLWlLwTVzIiFCxjpqN1ixq7XZWhTY/1i3De5q80h7ipDUkAuF3MnfM9LgrdShmrkU5TCjshRpOt/f8Df35BdGweff3lfeUKSXf9ryt6XzAf19ZUPNBJlEv6DtriRp1BxgiEgD5tZUVW7STREqjtO1uQJY2E9tMg93c6SryJgmZcwBLK5yjrIvf8GeVzqRiROG83lYJpYIwYFVLIQVti3Ih375qzeKXADLTwyclC/4mz6wnItRNlUW2sUifhTYQLsxiwFYySE9QRVIWTMLDk/4vsfSx7hC09taqoCn07+FPPO3d3WQAAD7wIJZCK3SSUfdgejWDaUr8g15T/PG7CoeN3vwWmk0Nd7t2Sa3MstePjjrJ2+hhfOpnyxR1NA12PnzL8fhsMA5MJV9KI/vLcXHag0fJ1Jr2igFHePbMA2r54fKzIyHQ2PfUMhjvFSaeCZpUt95ubvVh+qBjqejFVxxwxDzWeyHzTgcvLVwIc8cRrtotUH7BbgG75g=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
